name: app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^12.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  flutter_native_splash: ^2.3.5
  freezed_annotation: ^2.4.1
  fluttertoast: ^8.2.4
  http: ^1.1.0
  dio: ^5.3.3
  cached_network_image: ^3.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^8.1.0
  firebase_core: ^2.22.0
  firebase_messaging: ^14.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

flutter:
  uses-material-design: true
